"use client";

import { useEffect, useState } from "react";
import { finishesApi } from "@/lib/api/resources";
import type { AdFinish, FinishRevision } from "@/lib/types";
import { Button, Notice } from "./ui";
import { PrivateVideo } from "./private-media";

export function FinishEditor({generationId}:{generationId:string}) {
  const [finish,setFinish]=useState<AdFinish|null>(null); const [revision,setRevision]=useState<FinishRevision|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{finishesApi.list(generationId).then(items=>{if(items[0]){setFinish(items[0]);setRevision(items[0].revisions[0])}}).catch(e=>setError(e.message))},[generationId]);
  async function start(){setBusy(true);try{const item=await finishesApi.create(generationId);setFinish(item);setRevision(item.revisions[0])}catch(e){setError(e instanceof Error?e.message:"Finishing could not start.")}finally{setBusy(false)}}
  async function render(){if(!finish||!revision)return;setBusy(true);try{const saved=await finishesApi.update(finish.id,revision,crypto.randomUUID());const output=await finishesApi.render(finish.id,saved.id);setRevision({...saved,output_id:output.id})}catch(e){setError(e instanceof Error?e.message:"Finished ad could not be created.")}finally{setBusy(false)}}
  if(!finish)return <section className="card section"><p className="eyebrow">Finishing</p><h2>Turn this into a finished ad</h2><p>Add editable captions and finishing settings. Local finishing costs 0 credits.</p>{error&&<Notice kind="error">{error}</Notice>}<Button disabled={busy} onClick={()=>void start()}>Finish Ad</Button></section>;
  if(!revision)return null;
  return <section className="card section"><p className="eyebrow">Finishing · Version {revision.number}</p><h2>{revision.output_id?"Finished ad":"Finishing settings"}</h2>{error&&<Notice kind="error">{error}</Notice>}{revision.output_id&&<PrivateVideo load={()=>finishesApi.output(revision.output_id!)} filename={`adsyde-finished-${revision.output_id}.mp4`}/>}<label className="field"><input type="checkbox" checked={revision.captions_enabled} onChange={e=>setRevision({...revision,captions_enabled:e.target.checked})}/> Captions</label>{revision.caption_segments.map((segment,index)=><label className="field" key={segment.order}>Caption {index+1}<textarea value={segment.text} onChange={e=>setRevision({...revision,caption_segments:revision.caption_segments.map((item,i)=>i===index?{...item,text:e.target.value}:item)})}/></label>)}<label className="field"><input type="checkbox" checked={revision.voiceover_enabled} onChange={e=>setRevision({...revision,voiceover_enabled:e.target.checked})}/> Placeholder voice metadata</label><label className="field">Voice script<textarea value={revision.voice_script} onChange={e=>setRevision({...revision,voice_script:e.target.value})}/></label><label className="field">Music<select value={revision.music_key} onChange={e=>setRevision({...revision,music_key:e.target.value,music_enabled:e.target.value!=="none"})}>{["none","upbeat","minimal","elegant","energetic"].map(item=><option key={item}>{item}</option>)}</select></label><label className="field"><input type="checkbox" checked={revision.watermark_enabled} onChange={e=>setRevision({...revision,watermark_enabled:e.target.checked})}/> Development watermark configuration</label><p><small>The local renderer preserves these settings as metadata; it does not claim to burn captions, placeholder audio, or a watermark into the video.</small></p><div className="top-actions"><Button disabled={busy} onClick={()=>void render()}>Create finished ad</Button>{revision.output_id&&<Button variant="secondary" onClick={()=>finishesApi.captions(finish.id,revision.id,"srt").then(blob=>{const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download="adsyde-captions.srt";anchor.click();URL.revokeObjectURL(url)})}>Download captions</Button>}</div></section>;
}
